[package]
name = "rust-experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = {version = "1.6.0"}
rand = {version = "0.8.5"}
matrixmultiply = {version = "0.3.2"}
